export const SAVE_USER = 'SAVE_USER';
export const USER_LOADING = 'USER_LOADING';
export const HAVING_USER_REDUCER_ERROR = 'HAVING_USER_REDUCER_ERROR';

export const SAVE_APP = 'SAVE_APP';
export const APP_LOADING = 'APP_LOADING';
export const HAVING_APP_REDUCER_ERROR = 'HAVING_APP_REDUCER_ERROR';

export const SAVE_RATING = 'SAVE_RATING';
export const RATING_LOADING = 'RATING_LOADING';
export const HAVING_RATING_REDUCER_ERROR = 'HAVING_RATING_REDUCER_ERROR';